const config = {
    // Replace the Strapi logo in auth (login) views
    auth: {
        //  logo,
    },
    // Replace the favicon
    head: {
        //  favicon: logo,
    },
    // Replace the Strapi logo in the main navigation
    menu: {
        // logo,
    },
    // Extend the translations
    translations: {
        en: {
            "app.components.LeftMenu.navbrand.title": "Strapi",
            "app.components.LeftMenu.navbrand.workplace": "Miejsce pracy",
            "app.components.HomePage.welcome.again": "Witaj ponownie!",
            "app.components.HomePage.welcome.subtitle": "Miło Cię znowu widzieć, {{username}}!",
            "app.components.HomePage.button.blog": "Przejdź do bloga",
            "app.components.HomePage.welcome.congrats": "Gratulacje!",
            "app.components.HomePage.welcome.congrats.content": "Pomyślnie ukończyłeś konfigurację swojej aplikacji.",
            "app.components.HomePage.welcome.congrats.content.bold": "Teraz możesz zacząć budować swoje treści!",
            "app.components.HomePage.welcome.link": "Dowiedz się więcej na temat Strapi",
            "app.components.HomePage.welcome.video": "Zobacz wideo",
            "app.components.LeftMenuLinkContainer.collectionTypes": "Typy kolekcji",
            "app.components.LeftMenuLinkContainer.singleTypes": "Typy pojedyncze",
            "app.components.LeftMenuLinkContainer.plugins": "Pluginy",
            "app.components.LeftMenuLinkContainer.general": "Ogólne",
            "app.components.LeftMenuLinkContainer.settings": "Ustawienia",
            "app.components.ListPage.displayedEntries": "Wyświetl wpisy",
            "app.components.ListPage.delete": "Usuń",
            "app.components.ListPage.edit": "Edytuj",
            "app.components.ListPage.publish": "Publikuj",
            "app.components.ListPage.filter": "Filtruj",
            "app.components.ListPage.filters": "Filtry",
            "app.components.ListPage.clear": "Wyczyść",
            "app.components.ListPage.search": "Szukaj",
            "app.components.ListPage.bulkActions": "Operacje masowe",
            "app.components.ListPage.entriesPerPage": "Wpisów na stronę",
            "app.components.ListPage.select": "Wybierz",
            "app.components.ListPage.selected": "Wybrano",
            "app.components.ListPage.create": "Utwórz nowy wpis",
            "app.components.ListPage.entriesFound": "Znaleziono wpisy",
            "app.components.ListPage.sort": "Sortuj",
            "app.components.Input.text.placeholder": "Wpisz tutaj...",
            "app.components.Input.text.label": "Tekst",
            "app.components.Input.number.label": "Numer",
            "app.components.Input.boolean.label": "Wartość logiczna",
            "app.components.Input.date.label": "Data",
            "app.components.Input.select.label": "Wybierz",
            "app.components.Input.json.label": "JSON",
            "app.components.Input.file.label": "Plik",
            "app.components.Input.media.label": "Media",
            "app.components.Input.relation.label": "Relacja",
            "app.components.Input.select.defaultOption": "Wybierz opcję",
            "app.components.Button.save": "Zapisz",
            "app.components.Button.cancel": "Anuluj",
            "app.components.Button.delete": "Usuń",
            "app.components.Button.edit": "Edytuj",
            "app.components.Button.publish": "Publikuj",
            "app.components.Button.unpublish": "Cofnij publikację",
            "app.components.Button.add": "Dodaj",
            "app.components.Button.remove": "Usuń",
            "app.components.Button.confirm": "Potwierdź",
            "app.components.Button.close": "Zamknij",
            "app.components.Button.view": "Pokaż",
            "app.components.Button.upload": "Prześlij",
            "app.components.Header.logout": "Wyloguj się",
            "app.components.Header.profile": "Profil",
            "app.components.LeftMenu.logout": "Wyloguj się",
            "app.components.LeftMenu.documentation": "Dokumentacja",
            "app.components.LeftMenu.media": "Media",
            "app.components.LeftMenu.plugins": "Pluginy",
            "app.components.LeftMenu.settings": "Ustawienia",
            "app.components.LeftMenu.general": "Ogólne",
            "app.components.LeftMenu.marketplace": "Marketplace",
            "app.components.LeftMenu.collectionTypes": "Typy kolekcji",
            "app.components.LeftMenu.singleTypes": "Typy pojedyncze",
            "content-manager.components.EditView.add.newField": "Dodaj nowe pole",
            "content-manager.components.EditView.header.layout": "Układ",
            "content-manager.components.EditView.information": "Informacje",
            "content-manager.components.EditView.label": "Etykieta",
            "content-manager.components.EditView.relation": "Relacja",
            "content-manager.components.EditView.title": "Tytuł",
            "content-manager.components.ListView.header.label": "Etykieta",
            "content-manager.components.ListView.header.name": "Nazwa",
            "content-manager.components.ListView.header.type": "Typ",
            "content-manager.components.ListView.header.value": "Wartość",
            "content-manager.components.ListView.addFilter": "Dodaj filtr",
            "content-manager.components.ListView.clearAllFilters": "Wyczyść wszystkie filtry",
            "content-manager.components.ListView.filters": "Filtry",
            "content-manager.components.ListView.itemsPerPage": "Przedmioty na stronę",
            "content-manager.components.ListView.search": "Szukaj",
            "content-manager.components.ListView.showing": "Wyświetlanie",
            "content-manager.components.ListView.sortBy": "Sortuj według",
            "content-manager.components.ListView.total": "Łącznie",
            "content-manager.components.SettingsView.pluginDescription": "Opis pluginu",
            "content-manager.components.SettingsView.pluginName": "Nazwa pluginu",
            "content-manager.containers.EditSettingsView.description": "Edytuj ustawienia wyświetlania zawartości",
            "content-manager.containers.EditSettingsView.title": "Edytuj ustawienia",
            "content-manager.containers.HomePage.add": "Dodaj",
            "content-manager.containers.HomePage.description": "Zarządzaj treściami",
            "content-manager.containers.HomePage.name": "Nazwa",
            "content-manager.containers.HomePage.type": "Typ",
            "content-manager.containers.ListView.displayedEntries": "Wyświetlane wpisy",
            "content-manager.containers.ListView.entries": "Wpisy",
            "content-manager.containers.ListView.filters": "Filtry",
            "content-manager.containers.ListView.items": "Przedmioty",
            "content-manager.containers.ListView.search": "Szukaj",
            "content-manager.containers.ListView.showing": "Wyświetlanie",
            "content-manager.containers.ListView.total": "Łącznie",
            "content-manager.containers.SettingsPage.description": "Opis strony ustawień",
            "content-manager.containers.SettingsPage.title": "Strona ustawień",
            "content-manager.form.Input.select.placeholder": "Wybierz...",
            "content-manager.form.Input.text.placeholder": "Wpisz tekst...",
            "content-manager.form.button.add": "Dodaj",
            "content-manager.form.button.save": "Zapisz",
            "content-manager.form.button.cancel": "Anuluj",
            "content-manager.form.button.delete": "Usuń",
            "content-manager.form.button.edit": "Edytuj",
            "content-manager.form.button.publish": "Publikuj",
            "content-manager.form.button.unpublish": "Cofnij publikację",
            "content-manager.form.button.upload": "Prześlij",
            "content-manager.form.button.confirm": "Potwierdź",
            "content-manager.form.button.close": "Zamknij"
        },
    },
    // Disable video tutorials
    tutorials: false,
    // Disable notifications about new Strapi releases
    notifications: { releases: false },
};

const bootstrap = (app) => {
    console.log(app);
};

export default {
    config,
    bootstrap,
};